name: Run tests

on:
  workflow_dispatch:
  #push:
  #  branches: [main]
  #pull_request:
  #  branches: [main]

jobs:
  tests:
    name: Tests on ${{ matrix.python-version }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      matrix:
        # From wheel.yml of numpy (https://github.com/numpy/numpy/blob/main/.github/workflows/wheels.yml):
        # GitHub Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
          - [ ubuntu-22.04, manylinux_x86_64 ]
          - [ macos-12, macosx_x86_64 ]
          - [ macos-12, macosx_arm64 ]
          - [ windows-2022, win_amd64 ]
        python: [ "cp38", "cp312", "pp39" ]
        exclude:
          - buildplat: [ macos-12, macosx_arm64 ]
            python: "pp39"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          # Install local package with tests dependencies extras
          python -m pip install --upgrade pip
          pip install -e ".[tests]"

      - name: Test with pytest
        run: pytest --cov=./ --cov-report=xml -n auto --durations=0 -v

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
